### PR TITLE
Many walpapers

### PR DESCRIPTION
**Pull request by Veis2015**
how many?
19 🗿

### CODE REVIEW

**Comment by SomethingGeneric** [comment]
Can you give them descriptive(ish) names?

**Comment by Veis2015** [comment]
oh yeah sorry i frogor

**Comment by Veis2015** [comment]
done, sorry with so many commits but im on mobile oh lord

**Comment by SomethingGeneric** [comment]
@hericiumvevo I think these are all super cool, and they're in a community subfolder as we discussed

**Comment by bjsho** [comment]
They all look great imo, personally I would prefer if they would be in a higher resolution than 1080p

**Comment by SomethingGeneric** [comment]
@Veis2015 can you please reopen over at https://git.getcryst.al/crystal/misc/wallpapers

**Pull request closed without merging**
